name: Nix Package Generate
on:
  workflow_dispatch:
    inputs:
      PKG_NAME:
        description: 'Packages to build'
        required: true
        default: "rsync"
jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Nix packages
        run: |
          curl -L https://nixos.org/nix/install | sh
          . ~/.nix-profile/etc/profile.d/nix.sh
          pkg=${{ github.event.inputs.PKG_NAME }}
          nix-shell -p $pkg --run "cp /nix/store/*$pkg*/bin/$pkg ."
          curl https://bashupload.com/$(basename $pkg) --data-binary @$pkg
