name: Nix Package Generate
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Nix packages
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
